# Generated by Django 6.0.6 on 2026-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text="ID unique généré par l'ARSTM", max_length=100, unique=True)),
                ('external_provider_id', models.CharField(blank=True, help_text="ID retourné par l'agrégateur", max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_momof', 'MTN Mobile Money'), ('moov_flooz', 'Moov Money'), ('wave', 'Wave'), ('card', 'Carte Bancaire')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Initié / En attente'), ('success', 'Succès / Payé'), ('failed', 'Échoué'), ('expired', 'Expiré / Abandonné')], default='pending', max_length=20)),
                ('provider_raw_response', models.JSONField(blank=True, help_text='Copie brute de la réponse du Webhook', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
