# Generated by Django 6.0.6 on 2026-06-15 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('role', models.CharField(choices=[('student', 'Étudiant / Candidat'), ('professional', 'Professionnel / Entreprise'), ('recruiter', 'Recruteur / Partenaire RH'), ('donor', 'Bailleur de fonds / Partenaire Institutionnel'), ('researcher', 'Chercheur / Expert Maritime'), ('admin', 'Administrateur / Agent ARSTM (DCM)')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('must_change_password', models.BooleanField(default=False, help_text="Oblige l'utilisateur à changer son mot de passe à la prochaine connexion")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('position', models.CharField(max_length=255, verbose_name='Fonction / Titre')),
                ('organization_type', models.CharField(choices=[('ministry', 'Ministère / Administration publique'), ('multilateral', 'Organisation Multilatérale (UA, CEDEAO, OMI…)'), ('ngo', 'ONG / Fondation'), ('private', "Secteur Privé / Fondation d'entreprise"), ('other', 'Autre')], default='multilateral', max_length=20)),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Entreprise / Organisation')),
                ('job_title', models.CharField(max_length=255, verbose_name='Poste occupé')),
                ('sector', models.CharField(choices=[('maritime', 'Transport Maritime'), ('port', 'Logistique Portuaire'), ('offshore', 'Offshore / Industrie Navale'), ('security', 'Sûreté et Sécurité Maritime'), ('fishing', 'Pêche'), ('other', 'Autre')], default='maritime', max_length=20)),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='Site web (recruteurs)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_title', models.CharField(choices=[('dr', 'Dr.'), ('prof', 'Prof.'), ('mr', 'M.'), ('ms', 'Mme'), ('eng', 'Ing.')], default='dr', max_length=10)),
                ('institution', models.CharField(max_length=255, verbose_name='Institution / Laboratoire')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('research_profile_url', models.URLField(blank=True, null=True, verbose_name='Profil ORCID / ResearchGate')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.domain', verbose_name='Domaine de spécialisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='Département / Direction')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Matricule agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50, unique=True)),
                ('current_year', models.CharField(blank=True, help_text='Ex : Licence 2, Master 1', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
