# Generated by Django 6.0.6 on 2026-06-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant / Candidat'), ('professional', 'Professionnel / Entreprise'), ('recruiter', 'Recruteur / Partenaire RH'), ('donor', 'Bailleur de fonds / Partenaire Institutionnel'), ('researcher', 'Chercheur / Expert Maritime'), ('moderator', 'Modérateur ARSTM'), ('admin', 'Administrateur / Agent ARSTM (DCM)')], default='student', max_length=20),
        ),
    ]
