# Generated by Django 6.0.6 on 2026-06-16 11:30

import django.db.models.deletion
from django.db import migrations, models


def seed_lookup_values(apps, schema_editor):
    Sector = apps.get_model('users', 'Sector')
    OrganizationType = apps.get_model('users', 'OrganizationType')

    for order, (code, label) in enumerate((
        ('maritime', 'Transport Maritime'),
        ('port', 'Logistique Portuaire'),
        ('offshore', 'Offshore / Industrie Navale'),
        ('security', 'Sûreté et Sécurité Maritime'),
        ('fishing', 'Pêche'),
        ('other', 'Autre'),
    )):
        Sector.objects.create(code=code, label=label, order=order)

    for order, (code, label) in enumerate((
        ('ministry', 'Ministère / Administration publique'),
        ('multilateral', 'Organisation Multilatérale (UA, CEDEAO, OMI…)'),
        ('ngo', 'ONG / Fondation'),
        ('private', "Secteur Privé / Fondation d'entreprise"),
        ('other', 'Autre'),
    )):
        OrganizationType.objects.create(code=code, label=label, order=order)


def migrate_sector_values(apps, schema_editor):
    """Reporte l'ancienne valeur texte de `sector` vers la nouvelle FK, en se basant sur le `code`."""
    ProfessionalProfile = apps.get_model('users', 'ProfessionalProfile')
    Sector = apps.get_model('users', 'Sector')
    for profile in ProfessionalProfile.objects.exclude(sector_code=''):
        sector = Sector.objects.filter(code=profile.sector_code).first()
        if sector:
            profile.sector_new_id = sector.id
            profile.save(update_fields=['sector_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_lookup_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='researcherprofile',
            name='academic_title',
            field=models.CharField(choices=[('dr', 'Dr.'), ('prof', 'Prof.'), ('mr', 'M.'), ('ms', 'Mme'), ('ml', 'Mle'), ('eng', 'Ing.')], default='dr', max_length=10),
        ),
        migrations.AlterField(
            model_name='institutionalprofile',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutional_profiles', to='users.organizationtype'),
        ),
        # `sector` passe de CharField à ForeignKey : on renomme l'ancien champ pour
        # garder la donnée existante lisible, on ajoute la nouvelle FK, on copie les
        # valeurs par correspondance de `code`, puis on supprime l'ancien champ.
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='sector',
            new_name='sector_code',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='sector_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles', to='users.sector'),
        ),
        migrations.RunPython(migrate_sector_values, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='sector_code',
        ),
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='sector_new',
            new_name='sector',
        ),
    ]
