# Generated by Django 6.0.6 on 2026-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidat / Postulant'), ('student', 'Étudiant'), ('professional', 'Professionnel / Entreprise'), ('recruiter', 'Recruteur / Partenaire RH'), ('donor', 'Bailleur de fonds / Partenaire Institutionnel'), ('researcher', 'Chercheur / Expert Maritime'), ('moderator', 'Modérateur ARSTM'), ('admin', 'Administrateur / Agent ARSTM (DCM)')], default='student', max_length=20),
        ),
    ]
