# Generated by Django 6.0.6 on 2026-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_competition_model_and_candidate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_competition_notifications',
            field=models.BooleanField(default=True, help_text="L'utilisateur reçoit les emails lors de l'ouverture d'un nouveau concours"),
        ),
    ]
