# Generated by Django 6.0.6 on 2026-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Date et heure de début')),
                ('end_date', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('actualite', 'Actualité institutionnelle'), ('communique', 'Communiqué de presse'), ('revue_presse', 'Revue de presse')], default='actualite', max_length=20)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('content_fr', models.TextField(null=True, verbose_name='Contenu')),
                ('content_en', models.TextField(null=True, verbose_name='Contenu')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/news/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nom de la campagne')),
                ('image', models.ImageField(upload_to='events/banners/', verbose_name='Bannière')),
                ('image_fr', models.ImageField(null=True, upload_to='events/banners/', verbose_name='Bannière')),
                ('image_en', models.ImageField(null=True, upload_to='events/banners/', verbose_name='Bannière')),
                ('target_url', models.URLField(verbose_name='Lien de redirection')),
                ('is_active', models.BooleanField(default=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('start_display', models.DateTimeField()),
                ('end_display', models.DateTimeField()),
            ],
        ),
    ]
