# Generated by Django 6.0.6 on 2026-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_increase_slug_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé du concours')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Date limite de dépôt')),
                ('competition_date', models.DateField(blank=True, null=True, verbose_name='Date du concours')),
                ('is_active', models.BooleanField(default=False, verbose_name='Concours ouvert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
