# Generated by Django 6.0.6 on 2026-06-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('click', 'Clic'), ('download', 'Téléchargement'), ('view', 'Vue')], max_length=20)),
                ('visitor_country', models.CharField(blank=True, default='CI', help_text='Code pays ISO (ex: CI, BF, SN)', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='analytics_c_content_d24358_idx'), models.Index(fields=['timestamp'], name='analytics_c_timesta_dd0641_idx')],
            },
        ),
    ]
