# Generated by Django 6.0.6 on 2026-06-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé du poste')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('offer_type', models.CharField(choices=[('stage', 'Stage'), ('emploi', 'Emploi')], default='emploi', max_length=10)),
                ('organization', models.CharField(max_length=255, verbose_name='Entreprise / Institution')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('requirements', models.TextField(blank=True, verbose_name='Profil recherché / Prérequis')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite de candidature')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de Téléphone')),
                ('source', models.CharField(choices=[('contact', 'Formulaire de Contact général'), ('admission', 'Inscription / Admission Concours'), ('internship', 'Candidature Stage / Emploi')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'En cours de traitement / Contacté'), ('converted', 'Converti / Inscrit validé'), ('closed', 'Sans suite')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de capture')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('stage', 'Demande de Stage'), ('emploi', 'Candidature Spontanée / Emploi')], default='stage', max_length=15)),
                ('cv_file', models.FileField(upload_to='interactions/cvs/', verbose_name='Curriculum Vitae (PDF)')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Lettre de motivation / Message')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship_detail', to='interactions.lead')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_detail', to='interactions.lead')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(help_text='Ex: Baccalauréat, Licence 2', max_length=100)),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='academic.program')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_detail', to='interactions.lead')),
            ],
        ),
    ]
