# Generated by Django 6.0.6 on 2026-06-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_increase_slug_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Permet de gérer le désabonnement (Opt-out)', verbose_name='Abonnement Actif')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_detail', to='interactions.lead')),
            ],
        ),
    ]
