# Generated by Django 6.0.6 on 2026-06-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('program_type', models.CharField(choices=[('initiale', 'Formation Initiale'), ('continue', 'Formation Continue')], max_length=20)),
                ('regime', models.CharField(choices=[('sedentaire', 'Sédentaire'), ('navigant', 'Navigant')], default='sedentaire', max_length=20)),
                ('duration', models.CharField(help_text='Ex: 3 ans, 12 mois', max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('career_opportunities', models.TextField(help_text='Séparés par des retours à la ligne', verbose_name='Débouchés professionnels')),
                ('career_opportunities_fr', models.TextField(help_text='Séparés par des retours à la ligne', null=True, verbose_name='Débouchés professionnels')),
                ('career_opportunities_en', models.TextField(help_text='Séparés par des retours à la ligne', null=True, verbose_name='Débouchés professionnels')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO pour Google (max 70 car.)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Description SEO pour Google (max 160 car.)', max_length=160)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.domain')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institution.school')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='academic/brochures/')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements (KPI)')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academic.program')),
            ],
        ),
    ]
