# Generated by Django 6.0.6 on 2026-06-16 11:30

import django.db.models.deletion
from django.db import migrations, models


def seed_lookup_values(apps, schema_editor):
    ProgramType = apps.get_model('academic', 'ProgramType')
    Regime = apps.get_model('academic', 'Regime')

    for order, (code, label) in enumerate((
        ('initiale', 'Formation Initiale'),
        ('continue', 'Formation Continue'),
    )):
        ProgramType.objects.create(code=code, label=label, order=order)

    for order, (code, label) in enumerate((
        ('sedentaire', 'Sédentaire'),
        ('navigant', 'Navigant'),
    )):
        Regime.objects.create(code=code, label=label, order=order)


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_lookup_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academic.programtype'),
        ),
        migrations.AlterField(
            model_name='program',
            name='regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academic.regime'),
        ),
    ]
