# Generated by Django 6.0.6 on 2026-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_programtype_regime_alter_program_program_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
