# Generated by Django 6.0.6 on 2026-06-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_increase_slug_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meta_title',
        ),
    ]
