# Generated by Django 6.0.6 on 2026-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(default=False, help_text="Devient True dès qu'une transaction associée passe à 'success'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('product_type', models.CharField(choices=[('publication', 'Publication Scientifique / Revue'), ('study', 'Étude Sectorielle'), ('formation_continue', 'Module Court / FOAD')], max_length=30)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix en FCFA', max_digits=10)),
                ('file_attachment', models.FileField(blank=True, help_text='Fichier si produit numérique', null=True, upload_to='shop/products/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
