# Generated by Django 6.0.6 on 2026-06-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='institution/infrastructures/')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('regional', 'Régional / Institutionnel'), ('international', 'International'), ('corporate', 'Société Privée / Partenaire Métier')], max_length=20)),
                ('logo', models.ImageField(upload_to='institution/partners/')),
                ('website_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: École Supérieure de Navigation (ESN)', max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('presentation_video_url', models.URLField(blank=True, null=True, verbose_name='URL Vidéo de présentation')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='institution/schools/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('current_position', models.CharField(max_length=255, verbose_name='Poste actuel / Entreprise')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='institution/testimonials/')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Mettre en avant sur la page d'accueil")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='institution.school')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
