# Generated by Django 6.0.6 on 2026-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=255, verbose_name='Titre / Fonction')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Titre / Fonction')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Titre / Fonction')),
                ('photo', models.ImageField(upload_to='institution/directors/')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_fr', models.TextField(null=True, verbose_name='Message')),
                ('message_en', models.TextField(null=True, verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur la page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
