# Generated by Django 6.0.6 on 2026-06-16 11:30

import django.db.models.deletion
from django.db import migrations, models


def seed_lookup_values(apps, schema_editor):
    PartnerType = apps.get_model('institution', 'PartnerType')
    for order, (code, label) in enumerate((
        ('regional', 'Régional / Institutionnel'),
        ('international', 'International'),
        ('corporate', 'Société Privée / Partenaire Métier'),
    )):
        PartnerType.objects.create(code=code, label=label, order=order)


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_directormessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_lookup_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='institution.partnertype'),
        ),
    ]
