# Generated by Django 6.0.6 on 2026-06-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_partnertype_alter_partner_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name="Site web de l'école"),
        ),
    ]
