# Generated by Django 6.0.6 on 2026-06-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_add_school_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
