# Generated by Django 6.0.6 on 2026-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_increase_school_slug_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accreditation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Accréditation'),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='school',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du directeur'),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='school',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de création'),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
    ]
